# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"j\n\x04\x44\x61ta\x12&\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x16.test.Data.FieldsEntry\x1a:\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.test.Datum:\x02\x38\x01\"c\n\x05\x44\x61tum\x12\x16\n\x0cnumber_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12\"\n\x0cstruct_value\x18\x05 \x01(\x0b\x32\n.test.DataH\x00\x42\x06\n\x04kindb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATA_FIELDSENTRY._options = None
  _DATA_FIELDSENTRY._serialized_options = b'8\001'
  _DATA._serialized_start=20
  _DATA._serialized_end=126
  _DATA_FIELDSENTRY._serialized_start=68
  _DATA_FIELDSENTRY._serialized_end=126
  _DATUM._serialized_start=128
  _DATUM._serialized_end=227
# @@protoc_insertion_point(module_scope)
